version: "3.9"

services:
    db:
        container_name: patitasacasa-db
        image: postgres:15
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - patitasacasa-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: patitasacasa
        networks:
            - patitasacasa-network
    app:
        container_name: patitasacasa-api
        image: patitasacasa:dev
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
            - "ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=db;Port=5432;Database=patitasacasa;IntegratedSecurity=true"
        networks:
            - patitasacasa-network
        restart: on-failure
volumes:
    patitasacasa-data:
networks:
    patitasacasa-network:
        driver: bridge
